# Generated by Django 2.1.5 on 2019-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_energy_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='energyrecord',
            name='timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
