# Generated by Django 2.1.5 on 2019-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_energy_server', '0002_auto_20190210_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyrecord',
            name='delivered_actual',
        ),
        migrations.RemoveField(
            model_name='energyrecord',
            name='delivered_tariff1',
        ),
        migrations.RemoveField(
            model_name='energyrecord',
            name='delivered_tariff2',
        ),
        migrations.RemoveField(
            model_name='energyrecord',
            name='received_actual',
        ),
        migrations.RemoveField(
            model_name='energyrecord',
            name='received_tariff1',
        ),
        migrations.RemoveField(
            model_name='energyrecord',
            name='received_tariff2',
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='kwh_181',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='kwh_182',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='kwh_281',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='kwh_282',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='energyrecord',
            name='gas',
            field=models.IntegerField(null=True),
        ),
    ]
