# Generated by Django 2.1.5 on 2019-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_energy_server', '0003_auto_20190213_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_last_update', models.DateTimeField()),
            ],
        ),
    ]
