# Generated by Django 2.1.5 on 2019-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_energy_server', '0004_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('ID', models.IntegerField(null=True)),
                ('HardwareID', models.IntegerField(null=True)),
                ('DeviceID', models.IntegerField(null=True)),
                ('Unit', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=20, verbose_name='Name')),
                ('Type', models.IntegerField(null=True)),
                ('LastUpdate', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'DeviceStatus',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('DeviceRowID', models.IntegerField(null=True)),
                ('Value', models.IntegerField(null=True)),
                ('Usage', models.IntegerField(null=True)),
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'Meter',
            },
        ),
        migrations.CreateModel(
            name='MultiMeter',
            fields=[
                ('DeviceRowID', models.IntegerField(null=True)),
                ('Value1', models.IntegerField(null=True)),
                ('Value2', models.IntegerField(null=True)),
                ('Value3', models.IntegerField(null=True)),
                ('Value4', models.IntegerField(null=True)),
                ('Value5', models.IntegerField(null=True)),
                ('Value6', models.IntegerField(null=True)),
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'MultiMeter',
            },
        ),
    ]
