# Generated by Django 2.1.5 on 2019-03-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_energy_server', '0005_devicestatus_meter_multimeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('DeviceRowID', models.IntegerField(null=True)),
                ('Total', models.FloatField(null=True)),
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Rain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('DeviceRowID', models.IntegerField(null=True)),
                ('Temperature', models.FloatField(null=True)),
                ('Chill', models.FloatField(null=True)),
                ('Humidity', models.IntegerField(null=True)),
                ('Barometer', models.IntegerField(null=True)),
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('DeviceRowID', models.IntegerField(null=True)),
                ('Direction', models.IntegerField(null=True)),
                ('Speed', models.IntegerField(null=True)),
                ('Gust', models.IntegerField(null=True)),
                ('Date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Wind',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='barometer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='rain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='wind_direction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='wind_gust',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='energyrecord',
            name='wind_speed',
            field=models.IntegerField(null=True),
        ),
    ]
